site_name: okctl
site_description: 'The official production tool for Oslo kommune'
site_author: 'okctl authors'
repo_name: 'oslokommune/okctl'
repo_url: 'https://github.com/oslokommune/okctl'
copyright: 'Copyright &copy; 2020 Oslo kommune'
docs_dir: src
edit_uri: ""

nav:
  - Getting started:
      - 1. Install: getting-started/install.md
      - 2. Prerequisites: getting-started/prerequisites.md
      - 3. Create cluster: getting-started/create-cluster.md
      - 4. Run virtual environment: getting-started/run-virtual-environment.md
      - 5. Create application: getting-started/create-application.md
      - 6. View bundled applications: getting-started/view-bundled-applications.md
      - 7. Monitoring your cluster and applications: getting-started/monitoring.md
      - 8. Application addons: getting-started/application-addons.md
      - 9. Continuous integration: getting-started/continuous-integration.md
      - 10. Upgrading okctl: getting-started/upgrading.md
      - 11. Delete cluster: getting-started/delete-cluster.md
  - Building blocks:
      - buildingblocks/cloud.md
      - buildingblocks/github.md
      - buildingblocks/kubernetes.md
      - buildingblocks/argocd.md
  - About:
      - 'About': about/about.md
      - 'Resource Overview': about/resources.md
  - Help:
      - FAQ: help/faq.md
      - Running a Docker image in your cluster: help/docker-registry.md
      - Common issues: help/common-issues.md
      - Outdated common issues: help/outdated-common-issues.md

plugins:
  - git-revision-date
  - search

extra_css:
  - assets/stylesheets/fonts.css
  - assets/stylesheets/theme.css
  - assets/stylesheets/button.css
  - assets/stylesheets/center-container.css

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/images/favicon.png'
  logo: 'assets/images/ok-logo-black.png'
  font:
    text: 'Montserrat'
    code: 'Roboto Mono'
  palette:
    primary: 'white'
    accent: 'light blue'
    scheme: default
  features:
    - header.hide
    - search.highlight
  highlightjs: true
  icon:
    repo: fontawesome/brands/github
  hljs_languages:
    - yaml
    - json
    - bash

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
